version: '3'
services:
  db:
    restart: always
    image: postgres:15.3
    container_name: money-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
  backend:
    restart: always
    image: robertorob3/money-backend:3.0.1
    container_name: money-backend
    ports:
     - "5299:8080"
    volumes:
     - ./money-backend/appsettings.override.json:/publish/appsettings.json
  ui:
    restart: always
    image: robertorob3/money-ui:3.1.2
    container_name: money-ui
    ports:
      - "80:80"
    volumes:
     - ./money-ui/.env.production:/app/.env.production
