version: '3'
services:
  db:
    restart: always
    image: postgres:15.3
    container_name: money-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./money-db:/var/lib/postgresql/data
  backend:
    restart: always
    image: robertorob3/money-backend:1.0.0
    container_name: money-backend
    ports:
     - "5299:80"
    volumes:
     - ./money-backend/appsettings.override.json:/app/appsettings.json
  ui:
    restart: always
    image: robertorob3/money-ui:1.0.4
    container_name: money-ui
    ports:
      - "80:80"
    extra_hosts:
      - "money-backend:host-gateway"
